# Generated by Django 4.1.7 on 2023-06-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_hmac_authentication", "0002_apihmackey_failed_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="apihmackey",
            name="expires_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="Expires at",
            ),
        ),
    ]
