# Generated by Django 4.1.7 on 2023-12-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_hmac_authentication", "0005_alter_apihmackey_throttle_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="apihmackey",
            name="cipher_algorithm",
            field=models.CharField(
                default="AES-256",
                editable=False,
                max_length=24,
                verbose_name="Cipher algorithm",
            ),
        ),
    ]
