# Generated by Django 4.2.15 on 2024-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_hmac_authentication", "0006_apihmackey_cipher_algorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="apihmackey",
            name="test_mode",
            field=models.BooleanField(default=False, verbose_name="Test mode?"),
        ),
    ]
